/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * The info of the warehouse where this stock is managed (stored)
 */
export type basicInfoWarehouseDto = {
    /**
     * The generated by Qilin when creating a new brand
     */
    id?: string;
    /**
     * The name of the warehouse
     */
    name?: Record<string, string>;
};

