/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * The basic info of product
 */
export type basicInfoProductDto = {
    /**
     * The generated by Qilin when creating a new product.
     */
    id?: string;
    /**
     * The title of the product
     */
    title?: Record<string, string>;
};

