/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { basicInfoChannelOfferDto } from './basicInfoChannelOfferDto';
import type { basicInfoProductDto } from './basicInfoProductDto';
import type { basicInfoVariationDto } from './basicInfoVariationDto';
export type headBasicInfoOfferDto = {
    /**
     * The generated by Qilin when creating a new offer.
     */
    id?: string;
    product?: basicInfoProductDto;
    variation?: basicInfoVariationDto;
    /**
     * A list of channel offers
     */
    channelOffers?: Array<basicInfoChannelOfferDto>;
};

