/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { channelOfferDetailDto } from './channelOfferDetailDto';
export type offerDetailDto = {
    /**
     * The generated by Qilin when creating a new offer.
     */
    id?: string;
    /**
     * The externalId defined outside Qilin
     */
    offerId?: string;
    /**
     * A list full of store specific offers for the referenced product.
     */
    channelOffers?: Array<channelOfferDetailDto>;
    /**
     * The latest update time of this offer.
     */
    updatedDate?: string;
    /**
     * Reference to the UUID of a product or variation created via API.
     */
    productOrVariationId?: string;
    updatedDateExternal?: string | null;
    hashValue?: string;
};

