/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { addressDetailDto } from './addressDetailDto';
export type warehouseDetailDto = {
    /**
     * The generated by Qilin when creating a new warehouse.
     */
    id?: string;
    /**
     * The externalId defined outside Qilin
     */
    warehouseId?: string;
    address?: addressDetailDto;
    /**
     * The latest update time of this offer.
     */
    updatedDate?: string;
    /**
     * The name of the warehouse
     */
    name?: Record<string, string>;
    /**
     * If the warehouse is an external fulfiller
     */
    isExternalFulfillment?: boolean;
    /**
     * Updated date defined outside Qilin
     */
    updatedDateExternal?: string;
    /**
     * The hash value to compare object
     */
    hashValue?: string;
};

