/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { noteDetailDto } from './noteDetailDto';
import type { purchaseOrderLineItemDetailDto } from './purchaseOrderLineItemDetailDto';
export type cancellationDetailDto = {
    /**
     * The generated by Qilin when creating a new Cancellation.
     */
    id?: string;
    /**
     * Notes on this cancellation.
     */
    notes?: Array<noteDetailDto> | null;
    /**
     * A list of order items that have been cancelled.
     */
    purchaseOrderLineItems?: Array<purchaseOrderLineItemDetailDto> | null;
    /**
     * The latest update time.
     */
    updatedDate?: string;
    /**
     * The state name of the cancellation
     */
    stateName?: string;
    /**
     * Reference to the ID of cancellation in the channel
     */
    cancellationId: string;
    /**
     * The status of the cancellation<br/>
     * Value:<br/>
     * 0: Requested<br/>
     * 1: Acknowledged<br/>
     * 2: Rejected<br/>
     * 3: Finished
     */
    state: cancellationDetailDto.state;
    /**
     * The reason for the cancellation request
     */
    requestReason?: string | null;
    /**
     * The reason for the rejection of the cancellation request
     */
    rejectReason?: string | null;
    /**
     * A list of additional options to this cancellation
     */
    options?: Record<string, Record<string, any>>;
};
export namespace cancellationDetailDto {
    /**
     * The status of the cancellation<br/>
     * Value:<br/>
     * 0: Requested<br/>
     * 1: Acknowledged<br/>
     * 2: Rejected<br/>
     * 3: Finished
     */
    export enum state {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
        '_3' = 3,
    }
}

