/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { noteDetailDto } from './noteDetailDto';
import type { packageDetailDto } from './packageDetailDto';
export type deliveryNoteDetailDto = {
    /**
     * The generated by Qilin when creating a new Delivery Note.
     */
    id?: string;
    /**
     * A list of packages.
     */
    packages?: Array<packageDetailDto>;
    /**
     * Notes on this delivery bill..
     */
    notes?: Array<noteDetailDto>;
    /**
     * The latest update time.
     */
    updatedDate?: string;
    /**
     * The time when this delivery bill was created.
     */
    deliveryNoteCreatedDate: string;
    /**
     * A list of additional options to this delivery bill..
     */
    options?: Record<string, Record<string, any>>;
};

