/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type feedbackDetailDto = {
    /**
     * The generated by Qilin when creating a new feedback.
     */
    id?: string;
    /**
     * Who wrote the review.
     */
    sourceName?: string;
    /**
     * Who or what was evaluated.
     */
    targetName?: string;
    /**
     * the reply of this feedback come from Target.
     */
    repliedFeedbackId?: string;
    /**
     * The latest update time.
     */
    updatedDate?: string;
    /**
     * The id from source who is create this feedback. It's used for recognize which feedback is replied
     */
    feedbackId: string;
    /**
     * Who wrote the review<br/>
     * The data type of the source<br/>
     * Value:<br/>
     * 0: Product<br/>
     * 1: Customer<br/>
     * 2: Marketplace<br/>
     * 3: Qilin<br/>
     * 4: Merchant<br/>
     * 5: Fulfiller<br/>
     * 6: Carrier<br/>
     * 7: PaymentServiceProvider<br/>
     * 8: Other
     */
    source?: feedbackDetailDto.source | null;
    /**
     * Who or what was evaluated<br/>
     * The data type of the Target<br/>
     * Value:<br/>
     * 0: Product<br/>
     * 1: Customer<br/>
     * 2: Marketplace<br/>
     * 3: Qilin<br/>
     * 4: Merchant<br/>
     * 5: Fulfiller<br/>
     * 6: Carrier<br/>
     * 7: PaymentServiceProvider<br/>
     * 8: Other
     */
    target?: feedbackDetailDto.target | null;
    /**
     * The rating, where 0 = the worst value and 100 = the best value.
     */
    rate?: number | null;
    /**
     * Reference where the rating comes from (e.g. ID of the customer, the merchant, the marketplace, ...)
     */
    sourceReference?: string | null;
    /**
     * Reference to which the evaluation refers (e.g. ID of an order item, ID of a customer, ID of a merchant, ID of a shipment, ID of a payment transaction, ...).
     */
    targetReference?: string | null;
    /**
     * The subject of the evaluation
     */
    subject?: Record<string, string>;
    /**
     * The summary of the evaluation
     */
    shortText?: Record<string, string>;
    /**
     * The detailed assessment
     */
    longText?: Record<string, string>;
};
export namespace feedbackDetailDto {
    /**
     * Who wrote the review<br/>
     * The data type of the source<br/>
     * Value:<br/>
     * 0: Product<br/>
     * 1: Customer<br/>
     * 2: Marketplace<br/>
     * 3: Qilin<br/>
     * 4: Merchant<br/>
     * 5: Fulfiller<br/>
     * 6: Carrier<br/>
     * 7: PaymentServiceProvider<br/>
     * 8: Other
     */
    export enum source {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
        '_3' = 3,
        '_4' = 4,
        '_5' = 5,
        '_6' = 6,
        '_7' = 7,
        '_8' = 8,
    }
    /**
     * Who or what was evaluated<br/>
     * The data type of the Target<br/>
     * Value:<br/>
     * 0: Product<br/>
     * 1: Customer<br/>
     * 2: Marketplace<br/>
     * 3: Qilin<br/>
     * 4: Merchant<br/>
     * 5: Fulfiller<br/>
     * 6: Carrier<br/>
     * 7: PaymentServiceProvider<br/>
     * 8: Other
     */
    export enum target {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
        '_3' = 3,
        '_4' = 4,
        '_5' = 5,
        '_6' = 6,
        '_7' = 7,
        '_8' = 8,
    }
}

