/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { messageSender } from './messageSender';
export type messageDetailDto = {
    /**
     * The generated by Qilin when creating a new message.
     */
    id?: string;
    /**
     * Channel where message come from<br/>
     * Value:<br/>
     * 0: Product<br/>
     * 1: Customer<br/>
     * 2: Marketplace<br/>
     * 3: Qilin<br/>
     * 4: Merchant<br/>
     * 5: Fulfiller<br/>
     * 6: Carrier<br/>
     * 7: PaymentServiceProvider<br/>
     * 8: Other<br/>
     */
    messageFromName?: string;
    /**
     * The text of the message.
     */
    text: string;
    /**
     * When was this message created.
     */
    createdDate?: string;
    /**
     * Where does message come from.
     */
    messageFrom: messageDetailDto.messageFrom;
    /**
     * Attached file send from sender.
     */
    fileAttached?: string;
    sender: messageSender;
};
export namespace messageDetailDto {
    /**
     * Where does message come from.
     */
    export enum messageFrom {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
        '_3' = 3,
        '_4' = 4,
        '_5' = 5,
        '_6' = 6,
        '_7' = 7,
        '_8' = 8,
    }
}

