/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { addressDetailDto } from './addressDetailDto';
import type { contactDetailDto } from './contactDetailDto';
import type { noteDetailDto } from './noteDetailDto';
import type { purchaseOrderLineItemDetailDto } from './purchaseOrderLineItemDetailDto';
import type { shippingInfoDetailDto } from './shippingInfoDetailDto';
export type packageDetailDto = {
    /**
     * The generated by Qilin when creating a new Package.
     */
    id?: string;
    /**
     * A list of items that will be shipped in this package.
     */
    purchaseOrderLineItems?: Array<purchaseOrderLineItemDetailDto>;
    shippingInfo?: shippingInfoDetailDto;
    returnShippingInfo?: shippingInfoDetailDto;
    fulfillmentAddress?: addressDetailDto;
    receiverAddress?: addressDetailDto;
    /**
     * Notes on this package.
     */
    notes?: Array<noteDetailDto> | null;
    contact?: contactDetailDto;
    /**
     * The latest update time.
     */
    updatedDate?: string;
    /**
     * A list of packages.
     */
    shipmentDate: string;
    /**
     * The height of the package in cm.
     */
    height?: number | null;
    /**
     * The width of the package in cm.
     */
    width?: number | null;
    /**
     * The length of the package in cm.
     */
    length?: number | null;
    /**
     * The weight of the package in grams.
     */
    weight?: number | null;
    /**
     * Hazard labeling.
     */
    hazardCodes?: Array<string> | null;
    /**
     * A list of additional options to this package.
     */
    options?: Record<string, Record<string, any>>;
};

