/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { fee } from './fee';
import type { money } from './money';
import type { paymentDetailDto } from './paymentDetailDto';
import type { paymentMethodDetailDto } from './paymentMethodDetailDto';
import type { voucherDetailDto } from './voucherDetailDto';
/**
 * Payment information.
 */
export type paymentInfoDetailDto = {
    /**
     * The generated by Qilin when creating a new payment info.
     */
    id?: string;
    /**
     * Reference to the ID of the Order.
     */
    orderId?: string;
    /**
     * List of Payment Detail
     */
    payments?: Array<paymentDetailDto>;
    paymentMethod?: paymentMethodDetailDto;
    /**
     * A list of coupons for this order
     */
    vouchers?: Array<voucherDetailDto> | null;
    /**
     * The latest update time.
     */
    updatedDate?: string;
    /**
     * Reference to the ID of the payment info in the channel.
     */
    paymentInfoId: string;
    /**
     * A list of additional costs (costs for the buyer). The Key indicates the name of the additional cost, the Value contains information about the amount of the additional cost and currency.
     */
    additionalCost: Record<string, money>;
    orderValue: money;
    /**
     * A list of fees for the trader for this order
     */
    fees: Array<fee>;
};

