/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { deliveryNoteDetailDto } from './deliveryNoteDetailDto';
import type { noteDetailDto } from './noteDetailDto';
export type shipmentDetailDto = {
    /**
     * The generated by Qilin when creating a new Shipment.
     */
    id?: string;
    /**
     * A ruse with delivery bills.
     */
    deliveryNotes?: Array<deliveryNoteDetailDto>;
    /**
     * Notes on this package.
     */
    notes?: Array<noteDetailDto>;
    /**
     * The latest update time.
     */
    updatedDate?: string;
    /**
     * The time when the package was shipped (handed over to the carrier)
     */
    shipmentCreatedDate: string;
    /**
     * A list of additional options to this package.
     */
    options?: Record<string, Record<string, any>>;
};

