/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { addressDetailDto } from './addressDetailDto';
export type brandDetailDto = {
    /**
     * The generated by Qilin when creating a new brand.
     */
    id?: string;
    /**
     * The latest update time of this brand.
     */
    updatedDate?: string;
    /**
     * The addresses
     */
    addresses?: Array<addressDetailDto> | null;
    /**
     * The externalId defined outside Qilin
     */
    brandId?: string;
    /**
     * The Id of input channel, where data goes from.
     */
    sourceId?: string;
    /**
     * The name of the brand
     */
    title: Record<string, string>;
    /**
     * A list of file URLs (image, mp3, mp4, etc)
     */
    mediaUrls?: Array<string> | null;
    /**
     * A list of URLs related to this brand
     */
    urLs?: Array<string> | null;
    /**
     * A list of email addresses for this brand
     */
    emails?: Array<string> | null;
    /**
     * Description of the brand
     */
    description?: Record<string, string>;
    /**
     * Custom attributes are defined by user
     */
    flexibleAttributes?: Record<string, Record<string, any>>;
    updatedDateExternal?: string | null;
    hashValue?: string;
};

