/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { productBaseInfo } from './productBaseInfo';
import type { productCategorizationInfo } from './productCategorizationInfo';
import type { productDto } from './productDto';
import type { productMetaInfo } from './productMetaInfo';
import type { productSeo } from './productSeo';
import type { productTextInfo } from './productTextInfo';
import type { productVariationInfo } from './productVariationInfo';
export type productDetailDto = {
    /**
     * The generated by Qilin when creating a new product.
     */
    id?: string;
    /**
     * The externalId defined outside Qilin
     */
    productId?: string;
    base?: productBaseInfo;
    text?: productTextInfo;
    meta?: productMetaInfo;
    seo?: productSeo;
    dimension?: productDto;
    /**
     * A list of file URLs (image, mp3, mp4, etc)
     */
    mediaUrls?: Array<string> | null;
    variation?: productVariationInfo;
    categorization?: productCategorizationInfo;
    other?: productDto;
    /**
     * Custom attributes are defined by user
     */
    flexibleAttributes?: Record<string, Record<string, any>>;
    /**
     * Date and time in Unix Timestamp Format (UTC) when the product was last updated.
     */
    updatedDate?: string;
    /**
     * The status of product
     */
    productStatus?: string | null;
    /**
     * The updated date external
     */
    updatedDateExternal?: string | null;
    /**
     * The hashvalue to compare data
     */
    hashValue?: string | null;
    /**
     * The Id of input channel, where data goes from.
     */
    sourceId?: string;
};

