events {
    worker_connections 1024;
}

http {
    upstream rails_api {
        server rails-api:3000;
    }
    
    upstream invoice_service {
        server invoice-service:8000;
    }

    server {
        listen 80;
        
        location /api/ {
            proxy_pass http://rails_api/;
        }
        
        location /invoice/ {
            proxy_pass http://invoice_service/;
        }
    }
}
