/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type qilinPermissionDetailDto = {
    /**
     * The generated by Qilin when creating a new item.
     */
    id?: string;
    /**
     * The permission name
     */
    qilinPermissionName?: string;
    /**
     * The type of Permission
     */
    permissionType?: qilinPermissionDetailDto.permissionType | null;
    /**
     * The type of Permission
     */
    permissionTypeName?: string | null;
    /**
     * The id of user who created this item
     */
    createdBy?: string;
    /**
     * The date when user updated this item
     */
    updatedDate?: string;
    /**
     * The id of user who updated this item
     */
    updatedBy?: string;
};
export namespace qilinPermissionDetailDto {
    /**
     * The type of Permission
     */
    export enum permissionType {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
    }
}

