/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type qilinActionDetailDto = {
    /**
     * The generated by Qilin when creating a new item.
     */
    id?: string;
    /**
     * The id of user who created this item
     */
    createdBy?: string;
    /**
     * The date when user updated this item
     */
    updatedDate?: string;
    /**
     * The id of user who updated this item
     */
    updatedBy?: string;
    /**
     * The name of this action
     */
    qilinActionName: string;
    /**
     * The description of this action
     */
    qilinActionDescription?: string | null;
};

