/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { qilinPermissionDetailDto } from './qilinPermissionDetailDto';
import type { qilinRoleDetailDto } from './qilinRoleDetailDto';
export type qilinUserDetailDto = {
    /**
     * The status of user
     */
    isActive?: boolean;
    /**
     * The type of user
     */
    userType?: qilinUserDetailDto.userType;
    /**
     * The name of user type
     */
    userTypeName?: string;
    /**
     * Azure AD id of user
     */
    azureId?: string;
    /**
     * The list of role of this user
     */
    qilinRoles?: Array<qilinRoleDetailDto>;
    /**
     * The list of permission of this user
     */
    qilinPermission?: Array<qilinPermissionDetailDto>;
    /**
     * The generated by Qilin when creating a new item.
     */
    id?: string;
    /**
     * The id of user who created this item
     */
    createdBy?: string;
    /**
     * The date when user created this item
     */
    createdDate?: string;
    /**
     * The date when user updated this item
     */
    updatedDate?: string;
    /**
     * The id of user who updated this item
     */
    updatedBy?: string;
    /**
     * The email of user
     */
    email: string;
    /**
     * The display name, will be set "{firstname} {lastname}" if empty
     */
    displayName?: string;
    /**
     * The first name of user
     */
    firstName?: string;
    /**
     * The last name of user
     */
    lastName?: string;
};
export namespace qilinUserDetailDto {
    /**
     * The type of user
     */
    export enum userType {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
        '_3' = 3,
    }
}

