/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { qilinUserDetailDto } from './qilinUserDetailDto';
export type qilinSubscriptionDetailDto = {
    /**
     * The generated by Qilin when creating a new item.
     */
    id?: string;
    /**
     * The id of user who created this item
     */
    createdBy?: string;
    /**
     * The date when user updated this item
     */
    updatedDate?: string;
    /**
     * The id of user who updated this item
     */
    updatedBy?: string;
    qilinUser?: qilinUserDetailDto;
    /**
     * The status of this subscription
     */
    isActive?: boolean;
    /**
     * The subscription name
     */
    subscriptionName: string;
};

