/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { qilinApiKeyLifeTimeDetailDto } from './qilinApiKeyLifeTimeDetailDto';
export type qilinApiKeyDetailDto = {
    /**
     * The generated by Qilin when creating a new item.
     */
    id?: string;
    lifeTime?: qilinApiKeyLifeTimeDetailDto;
    /**
     * The date when user updated this item
     */
    updatedDate?: string;
    /**
     * The generated key by Qilin when creating a new item.
     */
    key?: string;
    /**
     * Type of this api key.
     */
    typeName?: string;
    /**
     * The name of api key
     */
    name?: string;
    /**
     * Type of this api key.<br/>
     * Value:<br/>
     * 0: Duration<br/>
     * 1: ActiveTime<br/>
     * 2: Forever
     *
     */
    type: qilinApiKeyDetailDto.type;
};
export namespace qilinApiKeyDetailDto {
    /**
     * Type of this api key.<br/>
     * Value:<br/>
     * 0: Duration<br/>
     * 1: ActiveTime<br/>
     * 2: Forever
     *
     */
    export enum type {
        '_0' = 0,
        '_1' = 1,
        '_2' = 2,
    }
}

