#!/bin/bash
echo "======================================"
echo "   GoBD Platform - System Summary"
echo "======================================"
echo ""
echo "📦 Running Containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo ""
echo "💾 Database Tables:"
docker exec gobd-postgres psql -U gobd -d gobd_production -c "\dt"
echo ""
echo "📊 Invoice Statistics:"
docker exec gobd-postgres psql -U gobd -d gobd_production -c "SELECT status, COUNT(*) as count, SUM(total_amount) as total FROM invoices GROUP BY status;"
echo ""
echo "🔗 Blockchain Status:"
curl -s http://localhost:8000/blockchain | python3 -c "import sys, json; data=json.load(sys.stdin); print(f\"Blocks: {data['length']}\nLatest Hash: {data['chain'][-1]['hash'] if data['chain'] else 'N/A'}\")"
echo ""
echo "✅ System Health:"
curl -s http://localhost:8000/health | python3 -m json.tool
